import type { SphereId } from './site'

export type ProjectContent = {
  slug: string
  title: string
  year: number
  sphere: SphereId
  role: string
  context: string
  summary: string
  problem: string
  solution: string
  result: string
  tools: string[]
  tags: string[]
  hero: string
  gallery: string[]
  featured: boolean
  videoUrl?: string
}

export const projects: Record<'ru' | 'en', ProjectContent[]> = {
  ru: [
    {
      slug: 'field-lantern',
      title: 'BMW X6 Custom Tail Lights',
      year: 2025,
      sphere: 'industrial',
      role: 'Реверс-инжиниринг и производство',
      context: 'LedStudio',
      summary: 'Разработка и производство кастомных задних фонарей для BMW X6 с использованием передовых методов аддитивного производства.',
      problem: 'Необходимость создания высокоточных деталей, которые идеально интегрируются в оригинальный кузов автомобиля и соответствуют промышленным стандартам.',
      solution: 'Проведено высокоточное 3D-сканирование оригинальных запчастей, на основе которых в Blender была создана финальная модель. Для производства использовались два метода: печать из стеклонаполненного пластика на FDM-принтере для структурных элементов и полимерная смола на SLS-принтере для детализированных компонентов.',
      result: 'Созданы полностью функциональные кастомные фонари, объединяющие точность цифрового проектирования и прочность современных полимеров.',
      tools: ['3D Scanning', 'Blender', 'FDM Printing', 'SLS Printing'],
      tags: ['product', 'hard-surface'],
      hero: 'work/industrial-01/cover.png',
      gallery: ['work/industrial-01/cover.png', 'work/industrial-01/render_01.jpg', 'work/industrial-01/render_02.jpg', 'work/industrial-01/render_03.mp4'],
      featured: true,
    },
    {
      slug: 'rzd-statue',
      title: 'RZD Retro Station Statue',
      year: 2026,
      sphere: 'industrial',
      role: '3D-моделирование и производство',
      context: 'Конкурс для Ретровокзала РЖД',
      summary: 'Создание полноразмерной статуи человека с использованием крупногабаритной 3D-печати.',
      problem: 'Необходимость создать масштабный объект с высокой детализацией, который был бы структурно устойчивым и соответствовал художественному замыслу конкурса.',
      solution: 'Разработка оптимизированной модели для сегментированной печати, подбор материалов для обеспечения прочности конструкции и последующая постобработка поверхности.',
      result: 'Успешное производство и установка полноразмерной фигуры, продемонстрировавшей возможности аддитивных технологий в архитектурном и художественном оформлении.',
      tools: ['Blender', 'Large-scale 3D Printing', 'Post-processing'],
      tags: ['product', 'ergonomics'],
      hero: 'work/industrial-02/cover.png',
      gallery: [
        'work/industrial-02/cover.png',
        'work/industrial-02/render_01.jpg',
        'work/industrial-02/render_02.jpg',
        'work/industrial-02/render_03.jpg',
        'work/industrial-02/render_04.jpg',
        'work/industrial-02/render_05.jpg',
        'work/industrial-02/render_06.jpg',
        'work/industrial-02/render_07.jpg',
        'work/industrial-02/render_08.jpg',
      ],
      featured: true,
    },
    {
      slug: 'freelander-viking',
      title: 'Freelander "Viking" Tail Lights',
      year: 2024,
      sphere: 'industrial',
      role: 'Дизайн и производство',
      context: 'Кастомный проект',
      summary: 'Кастомные задние фонари для Land Rover Freelander в скандинавском стиле «Викинг».',
      problem: 'Создание уникального визуального стиля, объединяющего современный автомобиль с мифологическими мотивами, при сохранении функциональности освещения.',
      solution: 'Разработка дизайна с использованием символики викингов: изображение Мьёльнира и защитных рун на основных панелях, а также рунической вязи в элементах поворотов. Реализовано с помощью комбинации 3D-печати и лазерной резки.',
      result: 'Эксклюзивный комплект оптики с высокой детализацией гравировки и точной подгонкой под кузов автомобиля.',
      tools: ['Blender', '3D Printing', 'Laser Cutting'],
      tags: ['product', 'modular'],
      hero: 'work/industrial-03/cover.png',
      gallery: ['work/industrial-03/cover.png', 'work/industrial-03/render_01.mp4'],
      featured: false,
    },
    {
      slug: 'aks-74u',
      title: 'AKS-74U "Mistress of Copper Mountain"',
      year: 2023,
      sphere: 'game',
      role: '3D Artist',
      context: 'Первый Game-Ready проект',
      summary: 'Low-poly модель автомата АКС-74У, вдохновленная уральской сказкой «Хозяйка Медной горы».',
      problem: 'Первая попытка создать полноценную игровую модель с соблюдением технических ограничений.',
      solution: 'Оптимизация геометрии до 5986 полигонов и создание текстур разрешения 2K.',
      result: 'Готовый к интеграции ассет с детализированным визуалом и оптимизированной сеткой.',
      tools: ['Blender', 'Marmoset Toolbag', 'Substance 3D Painter'],
      tags: ['weapon', 'hard-surface', 'game-ready'],
      hero: 'work/game-01/cover.png',
      gallery: ['work/game-01/cover.png', 'work/game-01/render_01.png', 'work/game-01/render_02.png', 'work/game-01/render_03.png', 'work/game-01/render_04.png', 'work/game-01/render_05.png'],
      featured: true,
    },
    {
      slug: 'if-death-robot',
      title: 'IF death is like This',
      year: 2024,
      sphere: 'game',
      role: '3D Artist',
      context: 'Study project',
      summary: 'Персонажи игры «IF death is like This»: Game-ready роботы, созданные в рамках учебного проекта.',
      problem: 'Создание детализированных механических персонажей, подходящих для интеграции в игровой движок.',
      solution: 'Разработка оптимизированной топологии и качественных текстур для передачи индустриального стиля.',
      result: 'Набор Game-ready моделей роботов с полной настройкой материалов.',
      tools: ['Blender', 'Marmoset Toolbag', 'Substance 3D Painter', 'Unity'],
      tags: ['character', 'robot', 'game-ready'],
      hero: 'work/game-02/cover.png',
      gallery: ['work/game-02/cover.png', 'work/game-02/render_01.png', 'work/game-02/render_02.png', 'work/game-02/render_03.png'],
      featured: true,
    },
    {
      slug: 'breach-panel',
      title: 'Университет в VR',
      year: 2024,
      sphere: 'game',
      role: '3D Environment Artist',
      context: 'Масштабный проект для института · кампус УрФУ',
      summary: 'Создано более 150 уникальных объектов окружения и воссоздано строящееся здание кампуса УрФУ.',
      problem: 'Университету требовалось наглядно представить будущий кампус до завершения строительства — без дорогостоящих физических макетов.',
      solution: 'Полное 3D-воссоздание здания и масштабного окружения: тайловые ассеты, модульные объекты, PBR-материалы в Unreal Engine.',
      result: 'Работа позволила университету сэкономить более $100,000 на макетах и презентационных материалах.',
      tools: ['Blender', 'Substance 3D Painter', 'Unreal Engine'],
      tags: ['environment', 'archviz', 'game-ready'],
      hero: 'work/game-03/cover.jpg',
      gallery: ['work/game-03/cover.jpg', 'work/game-03/render_01.mp4', 'work/game-03/render_02.jpg', 'work/game-03/render_03.png', 'work/game-03/render_04.png', 'work/game-03/render_05.png'],
      featured: false,
    },
  ],
  en: [
    {
      slug: 'field-lantern',
      title: 'BMW X6 Custom Tail Lights',
      year: 2025,
      sphere: 'industrial',
      role: 'Reverse Engineering & Production',
      context: 'LedStudio',
      summary: 'Development and production of custom tail lights for BMW X6 using advanced additive manufacturing techniques.',
      problem: 'The need to create high-precision parts that integrate perfectly into the original car body and meet industrial standards.',
      solution: 'High-precision 3D scanning of original parts was performed, and a final model was created in Blender. Two production methods were used: glass-filled plastic on an FDM printer for structural elements and polymer resin on an SLS printer for detailed components.',
      result: 'Fully functional custom tail lights were created, combining the precision of digital design with the strength of modern polymers.',
      tools: ['3D Scanning', 'Blender', 'FDM Printing', 'SLS Printing'],
      tags: ['product', 'hard-surface'],
      hero: 'work/industrial-01/cover.png',
      gallery: ['work/industrial-01/cover.png', 'work/industrial-01/render_01.jpg', 'work/industrial-01/render_02.jpg', 'work/industrial-01/render_03.mp4'],
      featured: true,
    },
    {
      slug: 'rzd-statue',
      title: 'RZD Retro Station Statue',
      year: 2026,
      sphere: 'industrial',
      role: '3D Modeling & Production',
      context: 'RZD Retro Station Competition',
      summary: 'Creation of a full-scale human statue using large-format 3D printing.',
      problem: 'The need to create a large-scale object with high detail that remained structurally stable and aligned with the artistic vision of the competition.',
      solution: 'Development of an optimized model for segmented printing, selection of materials to ensure structural integrity, and subsequent surface post-processing.',
      result: 'Successful production and installation of a full-scale figure, demonstrating the capabilities of additive technologies in architectural and artistic design.',
      tools: ['Blender', 'Large-scale 3D Printing', 'Post-processing'],
      tags: ['product', 'ergonomics'],
      hero: 'work/industrial-02/cover.png',
      gallery: [
        'work/industrial-02/cover.png',
        'work/industrial-02/render_01.jpg',
        'work/industrial-02/render_02.jpg',
        'work/industrial-02/render_03.jpg',
        'work/industrial-02/render_04.jpg',
        'work/industrial-02/render_05.jpg',
        'work/industrial-02/render_06.jpg',
        'work/industrial-02/render_07.jpg',
        'work/industrial-02/render_08.jpg',
      ],
      featured: true,
    },
    {
      slug: 'freelander-viking',
      title: 'Freelander "Viking" Tail Lights',
      year: 2024,
      sphere: 'industrial',
      role: 'Design & Production',
      context: 'Custom Project',
      summary: 'Custom tail lights for Land Rover Freelander in a Scandinavian "Viking" style.',
      problem: 'Creating a unique visual style that blends a modern vehicle with mythological motifs while maintaining lighting functionality.',
      solution: 'Design development using Viking symbolism: Mjölnir and protective runes on the main panels, and runic script for the turn signals. Produced using a combination of 3D printing and laser cutting.',
      result: 'An exclusive lighting set with high-detail engraving and precise fit to the vehicle body.',
      tools: ['Blender', '3D Printing', 'Laser Cutting'],
      tags: ['product', 'modular'],
      hero: 'work/industrial-03/cover.png',
      gallery: ['work/industrial-03/cover.png', 'work/industrial-03/render_01.mp4'],
      featured: false,
    },
    {
      slug: 'aks-74u',
      title: 'AKS-74U "Mistress of Copper Mountain"',
      year: 2023,
      sphere: 'game',
      role: '3D Artist',
      context: 'First Game-Ready project',
      summary: 'Low-poly AKS-74U model based on the Ural fairy tale "Mistress of the Copper Mountain".',
      problem: 'First attempt to create a game-ready model while adhering to technical constraints.',
      solution: 'Geometry optimization to 5986 facets and creation of 2K textures.',
      result: 'Integration-ready asset with detailed visuals and optimized mesh.',
      tools: ['Blender', 'Marmoset Toolbag', 'Substance 3D Painter'],
      tags: ['weapon', 'hard-surface', 'game-ready'],
      hero: 'work/game-01/cover.png',
      gallery: ['work/game-01/cover.png', 'work/game-01/render_01.png', 'work/game-01/render_02.png', 'work/game-01/render_03.png', 'work/game-01/render_04.png', 'work/game-01/render_05.png'],
      featured: true,
    },
    {
      slug: 'if-death-robot',
      title: 'IF death is like This',
      year: 2024,
      sphere: 'game',
      role: '3D Artist',
      context: 'Study project',
      summary: 'Characters for the game "IF death is like This": Game-ready robots created as part of a studying project.',
      problem: 'Creating detailed mechanical characters suitable for game engine integration.',
      solution: 'Developing optimized topology and high-quality textures to convey an industrial style.',
      result: 'A set of Game-ready robot models with full material setup.',
      tools: ['Blender', 'Marmoset Toolbag', 'Substance 3D Painter', 'Unity'],
      tags: ['character', 'robot', 'game-ready'],
      hero: 'work/game-02/cover.png',
      gallery: ['work/game-02/cover.png', 'work/game-02/render_01.png', 'work/game-02/render_02.png', 'work/game-02/render_03.png'],
      featured: true,
    },
    {
      slug: 'breach-panel',
      title: 'University in VR',
      year: 2024,
      sphere: 'game',
      role: '3D Environment Artist',
      context: 'Large-scale project for an institute · UrFU campus',
      summary: 'Over 150 unique environment objects created and a reconstructing UrFU campus building brought to life.',
      problem: 'The university needed to showcase the future campus before construction was complete — without expensive physical models.',
      solution: 'Full 3D recreation of the building and extensive surroundings: tileable assets, modular objects, PBR materials in Unreal Engine.',
      result: 'The work allowed the university to save more than $100,000 on models and presentation materials.',
      tools: ['Blender', 'Substance 3D Painter', 'Unreal Engine'],
      tags: ['environment', 'archviz', 'game-ready'],
      hero: 'work/game-03/cover.jpg',
      gallery: ['work/game-03/cover.jpg', 'work/game-03/render_01.mp4', 'work/game-03/render_02.jpg', 'work/game-03/render_03.png', 'work/game-03/render_04.png', 'work/game-03/render_05.png'],
      featured: false,
    },
  ],
}
